### ISSUE TITLE
Banners Don't Scroll on Game Settings and Compendium Packs Tabs

### ISSUE THREAD

**Issue by Dumbhuman** [mouse0270/fantasy-rpg-ui#2] opened 2022-10-10 00:44 UTC
This module's looking pretty great so far.  I'm not switching to v10 for a while (there's some functionality I don't want to lose), but this UI gives me one more reason to look forward to the day I do make that jump!

I did notice some strange behavior though that I figured I should report.  The animated gif below should give you most of the pertinent details, but I'll also mention that this is running on the Foundry app.

![FantasyUI_ScrollError](https://user-images.githubusercontent.com/63615591/194786812-32d69c36-0535-492b-bb6e-b2570e11ce0c.gif)

**Comment by mouse0270** [comment] 2022-10-10 01:42
HAHA... Completely intended behavior... This is what happens when you program on a 4k monitor where scrollbars basically don't exist...

I know how to fix it and will have it patched in the next version. lol

**Comment by mouse0270** [comment] 2022-10-10 16:56
Should be resolved in v0.3.6b https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.3.6b

**Closed as completed by mouse0270** 2022-10-10 16:56 UTC

**Comment by Dumbhuman** [comment] 2022-10-10 18:22
Works for me!  Keep up the good work!
